name: danidani/text
typeName: danidani_text
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  - identifier: header
    useExistingField: true
    label: 'Header (It is NOT rendered in Frontend)'
  - identifier: longtext
    type: Textarea
    enableRichtext: true
    label: 'Text for the first column'
    required: false
    richtextConfiguration: full